### ISSUE TITLE
Analisar utilização de lib js-brasil

### ISSUE THREAD

**Issue by evandrogdn** [maviniciuus/af-helpers#3]
Analisar a utilização da lib js-brasil [Github: https://github.com/mariohmol/js-brasil ], para aprimorar ainda mais a classe TributaçãoBr

**Comment by maviniciuus** [comment]
Hoje com a lib:
[fnando/cpf_cnpj](https://github.com/fnando/cpf_cnpj)

Conseguimos entregar geração, validação e testes apenas de CPF, CNPJ.

---
Atualizando para:
[mariohmol/js-brasil](https://github.com/mariohmol/js-brasil)

Poderemos implementar funcionalidades extras:

CEP - http://geradorbrasileiro.com/cep.html
Inscricao Estadual - - http://geradorbrasileiro.com/inscricaoestadual.html Todos os estados do Brasil
RG - http://geradorbrasileiro.com/rg.html
Placa de carro - http://geradorbrasileiro.com/placa.html
Telefone - http://geradorbrasileiro.com/telefone.html
Celular - http://geradorbrasileiro.com/celular.html
Título de Eleitor - http://geradorbrasileiro.com/titulo.html
Processo da justiça - http://geradorbrasileiro.com/processo.html
Outros: currency, percentage, time (data/hora), number - http://geradorbrasileiro.com/others.html

**Comment by evandrogdn** [comment]
Analisando melhor a biblioteca em questão, usar a mesma para substituir a biblioteca anterior não irá atender da mesma maneira que a anterior já atende.

Porém a mesma ainda fornece algumas outras funções que podem contribuir para o projeto em questão, como geradores, validadores de CEP, Inscrição Estadual, RG, Placas de Veículo, Telefones, Celulares, Títulos de Eleitor e outros...

Novas issues serão abertas ao longo do tempo para as implementações citadas anteriormente, que irão agregar mais valor ao projeto
