### ISSUE TITLE
Melhoria de nomenclaturas de classes

### ISSUE THREAD

**Issue by evandrogdn** [maviniciuus/af-helpers#4]
Algumas classes, como por exemplo, TributacaoBR, poderiam ter uma melhoria em seus nomes, no momento, essa classe está realizando geração e validações de documentos, não se encaixando necessariamente no quesito de tributações.

A sugestão seria repensar e separar, se necessário, essas informações em novas classes para melhorar a organização e facilitar a utilidade da mesma.

**Comment by maviniciuus** [comment]
Acho uma boa, separar em classes referente ao tipo de entidade:

PessoaFisica
PessoaJuridica
PessoaCei
...

**Comment by maviniciuus** [comment]
O legal é manter a classe TributacaoBr como wrapper das novas classes... E então exibir console.error de deprecated quando alguém usar ela... Pra manter a retrocompatibilidade!

**Comment by maviniciuus** [comment]
@evandrogdn 
Faltou o warning pra avisar que é deprecated quando chamar pela classe TributacaoBr.
Como vai ser temporário até a próxima versão, pode colocar um argumento extra pra definir se printa o warning ou não...

**Comment by maviniciuus** [comment]
Adicionei o warning e algumas pendências...
